extends Resource
class_name AdminListChatMessages200ResponseDataInner

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# AdminListChatMessages200ResponseDataInner Model


# Required: False
# isArray: false
@export var chat_ref_id: int:
	set(value):
		__chat_ref_id__was__set = true
		chat_ref_id = value
var __chat_ref_id__was__set := false

# Required: False
# isArray: false
# Allowed values: "lobby", "group", "friend", "party"
@export var chat_type: String = "":
	set(value):
		if str(value) != "" and not (str(value) in __chat_type__allowable__values):
			push_error("AdminListChatMessages200ResponseDataInner: tried to set property `chat_type` to a value that is not allowed." +
				"  Allowed values: `lobby`, `group`, `friend`, `party`")
			return
		__chat_type__was__set = true
		chat_type = value
var __chat_type__was__set := false
var __chat_type__allowable__values := ["lobby", "group", "friend", "party"]

# Required: False
# isArray: false
@export var content: String = "":
	set(value):
		__content__was__set = true
		content = value
var __content__was__set := false

# Required: False
# isArray: false
@export var id: int:
	set(value):
		__id__was__set = true
		id = value
var __id__was__set := false

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var inserted_at: String:
	set(value):
		__inserted_at__was__set = true
		inserted_at = value
var __inserted_at__was__set := false

# Required: False
# isArray: false
@export var metadata: Dictionary:
	set(value):
		__metadata__was__set = true
		metadata = value
var __metadata__was__set := false

# Required: False
# isArray: false
@export var sender_email: String = "":
	set(value):
		__sender_email__was__set = true
		sender_email = value
var __sender_email__was__set := false

# Required: False
# isArray: false
@export var sender_id: int:
	set(value):
		__sender_id__was__set = true
		sender_id = value
var __sender_id__was__set := false

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var updated_at: String:
	set(value):
		__updated_at__was__set = true
		updated_at = value
var __updated_at__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__chat_ref_id__was__set:
		bzz_dictionary["chat_ref_id"] = self.chat_ref_id
	if self.__chat_type__was__set:
		bzz_dictionary["chat_type"] = self.chat_type
	if self.__content__was__set:
		bzz_dictionary["content"] = self.content
	if self.__id__was__set:
		bzz_dictionary["id"] = self.id
	if self.__inserted_at__was__set:
		bzz_dictionary["inserted_at"] = self.inserted_at
	if self.__metadata__was__set:
		bzz_dictionary["metadata"] = self.metadata
	if self.__sender_email__was__set:
		bzz_dictionary["sender_email"] = self.sender_email
	if self.__sender_id__was__set:
		bzz_dictionary["sender_id"] = self.sender_id
	if self.__updated_at__was__set:
		bzz_dictionary["updated_at"] = self.updated_at
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("chat_ref_id"):
		me.chat_ref_id = from_dict["chat_ref_id"]
	if from_dict.has("chat_type"):
		me.chat_type = from_dict["chat_type"]
	if from_dict.has("content"):
		me.content = from_dict["content"]
	if from_dict.has("id"):
		me.id = from_dict["id"]
	if from_dict.has("inserted_at"):
		me.inserted_at = from_dict["inserted_at"]
	if from_dict.has("metadata"):
		me.metadata = from_dict["metadata"]
	if from_dict.has("sender_email"):
		me.sender_email = from_dict["sender_email"]
	if from_dict.has("sender_id"):
		me.sender_id = from_dict["sender_id"]
	if from_dict.has("updated_at"):
		me.updated_at = from_dict["updated_at"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

