extends Resource
class_name AdminListSessions200ResponseDataInner

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# AdminListSessions200ResponseDataInner Model


#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var authenticated_at: String:
	set(value):
		__authenticated_at__was__set = true
		authenticated_at = value
var __authenticated_at__was__set := false

# Required: False
# isArray: false
@export var context: String = "":
	set(value):
		__context__was__set = true
		context = value
var __context__was__set := false

# Required: False
# isArray: false
@export var id: int:
	set(value):
		__id__was__set = true
		id = value
var __id__was__set := false

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var inserted_at: String:
	set(value):
		__inserted_at__was__set = true
		inserted_at = value
var __inserted_at__was__set := false

# Required: False
# isArray: false
@export var user_email: String = "":
	set(value):
		__user_email__was__set = true
		user_email = value
var __user_email__was__set := false

# Required: False
# isArray: false
@export var user_id: int:
	set(value):
		__user_id__was__set = true
		user_id = value
var __user_id__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__authenticated_at__was__set:
		bzz_dictionary["authenticated_at"] = self.authenticated_at
	if self.__context__was__set:
		bzz_dictionary["context"] = self.context
	if self.__id__was__set:
		bzz_dictionary["id"] = self.id
	if self.__inserted_at__was__set:
		bzz_dictionary["inserted_at"] = self.inserted_at
	if self.__user_email__was__set:
		bzz_dictionary["user_email"] = self.user_email
	if self.__user_id__was__set:
		bzz_dictionary["user_id"] = self.user_id
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("authenticated_at"):
		me.authenticated_at = from_dict["authenticated_at"]
	if from_dict.has("context"):
		me.context = from_dict["context"]
	if from_dict.has("id"):
		me.id = from_dict["id"]
	if from_dict.has("inserted_at"):
		me.inserted_at = from_dict["inserted_at"]
	if from_dict.has("user_email"):
		me.user_email = from_dict["user_email"]
	if from_dict.has("user_id"):
		me.user_id = from_dict["user_id"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

