extends Resource
class_name AdminUpdateLeaderboardRequest

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# AdminUpdateLeaderboardRequest Model


# Required: False
# isArray: false
@export var description: String = "":
	set(value):
		__description__was__set = true
		description = value
var __description__was__set := false

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var ends_at: String:
	set(value):
		__ends_at__was__set = true
		ends_at = value
var __ends_at__was__set := false

# Required: False
# isArray: false
@export var metadata: Dictionary:
	set(value):
		__metadata__was__set = true
		metadata = value
var __metadata__was__set := false

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var starts_at: String:
	set(value):
		__starts_at__was__set = true
		starts_at = value
var __starts_at__was__set := false

# Required: False
# isArray: false
@export var title: String = "":
	set(value):
		__title__was__set = true
		title = value
var __title__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__description__was__set:
		bzz_dictionary["description"] = self.description
	if self.__ends_at__was__set:
		bzz_dictionary["ends_at"] = self.ends_at
	if self.__metadata__was__set:
		bzz_dictionary["metadata"] = self.metadata
	if self.__starts_at__was__set:
		bzz_dictionary["starts_at"] = self.starts_at
	if self.__title__was__set:
		bzz_dictionary["title"] = self.title
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("description"):
		me.description = from_dict["description"]
	if from_dict.has("ends_at"):
		me.ends_at = from_dict["ends_at"]
	if from_dict.has("metadata"):
		me.metadata = from_dict["metadata"]
	if from_dict.has("starts_at"):
		me.starts_at = from_dict["starts_at"]
	if from_dict.has("title"):
		me.title = from_dict["title"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

