extends Resource
class_name AdminListNotifications200ResponseDataInner

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# AdminListNotifications200ResponseDataInner Model


# Notification body text
# Required: False
# isArray: false
@export var content: String = "":
	set(value):
		__content__was__set = true
		content = value
var __content__was__set := false

# Notification ID
# Required: False
# isArray: false
@export var id: int:
	set(value):
		__id__was__set = true
		id = value
var __id__was__set := false

# Timestamp (UTC) when the notification was created
#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var inserted_at: String:
	set(value):
		__inserted_at__was__set = true
		inserted_at = value
var __inserted_at__was__set := false

# Arbitrary metadata
# Required: False
# isArray: false
@export var metadata: Dictionary:
	set(value):
		__metadata__was__set = true
		metadata = value
var __metadata__was__set := false

# User ID of the recipient
# Required: False
# isArray: false
@export var recipient_id: int:
	set(value):
		__recipient_id__was__set = true
		recipient_id = value
var __recipient_id__was__set := false

# User ID of the sender
# Required: False
# isArray: false
@export var sender_id: int:
	set(value):
		__sender_id__was__set = true
		sender_id = value
var __sender_id__was__set := false

# Notification title
# Required: False
# isArray: false
@export var title: String = "":
	set(value):
		__title__was__set = true
		title = value
var __title__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__content__was__set:
		bzz_dictionary["content"] = self.content
	if self.__id__was__set:
		bzz_dictionary["id"] = self.id
	if self.__inserted_at__was__set:
		bzz_dictionary["inserted_at"] = self.inserted_at
	if self.__metadata__was__set:
		bzz_dictionary["metadata"] = self.metadata
	if self.__recipient_id__was__set:
		bzz_dictionary["recipient_id"] = self.recipient_id
	if self.__sender_id__was__set:
		bzz_dictionary["sender_id"] = self.sender_id
	if self.__title__was__set:
		bzz_dictionary["title"] = self.title
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("content"):
		me.content = from_dict["content"]
	if from_dict.has("id"):
		me.id = from_dict["id"]
	if from_dict.has("inserted_at"):
		me.inserted_at = from_dict["inserted_at"]
	if from_dict.has("metadata"):
		me.metadata = from_dict["metadata"]
	if from_dict.has("recipient_id"):
		me.recipient_id = from_dict["recipient_id"]
	if from_dict.has("sender_id"):
		me.sender_id = from_dict["sender_id"]
	if from_dict.has("title"):
		me.title = from_dict["title"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

