extends Resource
class_name AdminCreateNotificationRequest

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# AdminCreateNotificationRequest Model


# Notification body text (optional)
# Required: False
# isArray: false
@export var content: String = "":
	set(value):
		__content__was__set = true
		content = value
var __content__was__set := false

# Arbitrary metadata (optional)
# Required: False
# isArray: false
@export var metadata: Dictionary:
	set(value):
		__metadata__was__set = true
		metadata = value
var __metadata__was__set := false

# Recipient user ID
# Required: True
# isArray: false
@export var recipient_id: int:
	set(value):
		__recipient_id__was__set = true
		recipient_id = value
var __recipient_id__was__set := false

# Sender user ID
# Required: True
# isArray: false
@export var sender_id: int:
	set(value):
		__sender_id__was__set = true
		sender_id = value
var __sender_id__was__set := false

# Notification title (required)
# Required: True
# isArray: false
@export var title: String = "":
	set(value):
		__title__was__set = true
		title = value
var __title__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	if not self.__recipient_id__was__set:
		bzz_missing_properties.append("recipient_id")
	if not self.__sender_id__was__set:
		bzz_missing_properties.append("sender_id")
	if not self.__title__was__set:
		bzz_missing_properties.append("title")
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__content__was__set:
		bzz_dictionary["content"] = self.content
	if self.__metadata__was__set:
		bzz_dictionary["metadata"] = self.metadata
	if self.__recipient_id__was__set:
		bzz_dictionary["recipient_id"] = self.recipient_id
	if self.__sender_id__was__set:
		bzz_dictionary["sender_id"] = self.sender_id
	if self.__title__was__set:
		bzz_dictionary["title"] = self.title
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("content"):
		me.content = from_dict["content"]
	if from_dict.has("metadata"):
		me.metadata = from_dict["metadata"]
	if from_dict.has("recipient_id"):
		me.recipient_id = from_dict["recipient_id"]
	if from_dict.has("sender_id"):
		me.sender_id = from_dict["sender_id"]
	if from_dict.has("title"):
		me.title = from_dict["title"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

