extends Resource
class_name AdminSubmitLeaderboardScore200ResponseData

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# AdminSubmitLeaderboardScore200ResponseData Model


# Required: False
# isArray: false
@export var id: int:
	set(value):
		__id__was__set = true
		id = value
var __id__was__set := false

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var inserted_at: String:
	set(value):
		__inserted_at__was__set = true
		inserted_at = value
var __inserted_at__was__set := false

# Required: False
# isArray: false
@export var leaderboard_id: int:
	set(value):
		__leaderboard_id__was__set = true
		leaderboard_id = value
var __leaderboard_id__was__set := false

# Required: False
# isArray: false
@export var metadata: Dictionary:
	set(value):
		__metadata__was__set = true
		metadata = value
var __metadata__was__set := false

# Required: False
# isArray: false
@export var rank: int:
	set(value):
		__rank__was__set = true
		rank = value
var __rank__was__set := false

# Required: False
# isArray: false
@export var score: int:
	set(value):
		__score__was__set = true
		score = value
var __score__was__set := false

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var updated_at: String:
	set(value):
		__updated_at__was__set = true
		updated_at = value
var __updated_at__was__set := false

# Required: False
# isArray: false
@export var user_id: int:
	set(value):
		__user_id__was__set = true
		user_id = value
var __user_id__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__id__was__set:
		bzz_dictionary["id"] = self.id
	if self.__inserted_at__was__set:
		bzz_dictionary["inserted_at"] = self.inserted_at
	if self.__leaderboard_id__was__set:
		bzz_dictionary["leaderboard_id"] = self.leaderboard_id
	if self.__metadata__was__set:
		bzz_dictionary["metadata"] = self.metadata
	if self.__rank__was__set:
		bzz_dictionary["rank"] = self.rank
	if self.__score__was__set:
		bzz_dictionary["score"] = self.score
	if self.__updated_at__was__set:
		bzz_dictionary["updated_at"] = self.updated_at
	if self.__user_id__was__set:
		bzz_dictionary["user_id"] = self.user_id
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("id"):
		me.id = from_dict["id"]
	if from_dict.has("inserted_at"):
		me.inserted_at = from_dict["inserted_at"]
	if from_dict.has("leaderboard_id"):
		me.leaderboard_id = from_dict["leaderboard_id"]
	if from_dict.has("metadata"):
		me.metadata = from_dict["metadata"]
	if from_dict.has("rank"):
		me.rank = from_dict["rank"]
	if from_dict.has("score"):
		me.score = from_dict["score"]
	if from_dict.has("updated_at"):
		me.updated_at = from_dict["updated_at"]
	if from_dict.has("user_id"):
		me.user_id = from_dict["user_id"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

