extends Resource
class_name AdminUpdateGroup200Response

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# AdminUpdateGroup200Response Model


# Required: False
# isArray: false
@export var creator_id: int:
	set(value):
		__creator_id__was__set = true
		creator_id = value
var __creator_id__was__set := false

# Required: False
# isArray: false
@export var description: String = "":
	set(value):
		__description__was__set = true
		description = value
var __description__was__set := false

# Required: False
# isArray: false
@export var id: int:
	set(value):
		__id__was__set = true
		id = value
var __id__was__set := false

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var inserted_at: String:
	set(value):
		__inserted_at__was__set = true
		inserted_at = value
var __inserted_at__was__set := false

# Required: False
# isArray: false
@export var max_members: int:
	set(value):
		__max_members__was__set = true
		max_members = value
var __max_members__was__set := false

# Required: False
# isArray: false
@export var member_count: int:
	set(value):
		__member_count__was__set = true
		member_count = value
var __member_count__was__set := false

# Required: False
# isArray: false
@export var metadata: Dictionary:
	set(value):
		__metadata__was__set = true
		metadata = value
var __metadata__was__set := false

# Chat slowdown in seconds (0 = disabled)
# Required: False
# isArray: false
@export var slowdown: int:
	set(value):
		__slowdown__was__set = true
		slowdown = value
var __slowdown__was__set := false

# Required: False
# isArray: false
@export var title: String = "":
	set(value):
		__title__was__set = true
		title = value
var __title__was__set := false

# Required: False
# isArray: false
@export var type: String = "":
	set(value):
		__type__was__set = true
		type = value
var __type__was__set := false

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var updated_at: String:
	set(value):
		__updated_at__was__set = true
		updated_at = value
var __updated_at__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__creator_id__was__set:
		bzz_dictionary["creator_id"] = self.creator_id
	if self.__description__was__set:
		bzz_dictionary["description"] = self.description
	if self.__id__was__set:
		bzz_dictionary["id"] = self.id
	if self.__inserted_at__was__set:
		bzz_dictionary["inserted_at"] = self.inserted_at
	if self.__max_members__was__set:
		bzz_dictionary["max_members"] = self.max_members
	if self.__member_count__was__set:
		bzz_dictionary["member_count"] = self.member_count
	if self.__metadata__was__set:
		bzz_dictionary["metadata"] = self.metadata
	if self.__slowdown__was__set:
		bzz_dictionary["slowdown"] = self.slowdown
	if self.__title__was__set:
		bzz_dictionary["title"] = self.title
	if self.__type__was__set:
		bzz_dictionary["type"] = self.type
	if self.__updated_at__was__set:
		bzz_dictionary["updated_at"] = self.updated_at
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("creator_id"):
		me.creator_id = from_dict["creator_id"]
	if from_dict.has("description"):
		me.description = from_dict["description"]
	if from_dict.has("id"):
		me.id = from_dict["id"]
	if from_dict.has("inserted_at"):
		me.inserted_at = from_dict["inserted_at"]
	if from_dict.has("max_members"):
		me.max_members = from_dict["max_members"]
	if from_dict.has("member_count"):
		me.member_count = from_dict["member_count"]
	if from_dict.has("metadata"):
		me.metadata = from_dict["metadata"]
	if from_dict.has("slowdown"):
		me.slowdown = from_dict["slowdown"]
	if from_dict.has("title"):
		me.title = from_dict["title"]
	if from_dict.has("type"):
		me.type = from_dict["type"]
	if from_dict.has("updated_at"):
		me.updated_at = from_dict["updated_at"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

