extends Resource
class_name AdminCreateLeaderboardRequest

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# AdminCreateLeaderboardRequest Model


# Required: False
# isArray: false
@export var description: String = "":
	set(value):
		__description__was__set = true
		description = value
var __description__was__set := false

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var ends_at: String:
	set(value):
		__ends_at__was__set = true
		ends_at = value
var __ends_at__was__set := false

# Required: False
# isArray: false
@export var metadata: Dictionary:
	set(value):
		__metadata__was__set = true
		metadata = value
var __metadata__was__set := false

# Required: False
# isArray: false
# Allowed values: "set", "best", "incr", "decr"
@export var operator: String = "":
	set(value):
		if str(value) != "" and not (str(value) in __operator__allowable__values):
			push_error("AdminCreateLeaderboardRequest: tried to set property `operator` to a value that is not allowed." +
				"  Allowed values: `set`, `best`, `incr`, `decr`")
			return
		__operator__was__set = true
		operator = value
var __operator__was__set := false
var __operator__allowable__values := ["set", "best", "incr", "decr"]

# Required: True
# isArray: false
@export var slug: String = "":
	set(value):
		__slug__was__set = true
		slug = value
var __slug__was__set := false

# Required: False
# isArray: false
# Allowed values: "desc", "asc"
@export var sort_order: String = "":
	set(value):
		if str(value) != "" and not (str(value) in __sort_order__allowable__values):
			push_error("AdminCreateLeaderboardRequest: tried to set property `sort_order` to a value that is not allowed." +
				"  Allowed values: `desc`, `asc`")
			return
		__sort_order__was__set = true
		sort_order = value
var __sort_order__was__set := false
var __sort_order__allowable__values := ["desc", "asc"]

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var starts_at: String:
	set(value):
		__starts_at__was__set = true
		starts_at = value
var __starts_at__was__set := false

# Required: True
# isArray: false
@export var title: String = "":
	set(value):
		__title__was__set = true
		title = value
var __title__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	if not self.__slug__was__set:
		bzz_missing_properties.append("slug")
	if not self.__title__was__set:
		bzz_missing_properties.append("title")
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__description__was__set:
		bzz_dictionary["description"] = self.description
	if self.__ends_at__was__set:
		bzz_dictionary["ends_at"] = self.ends_at
	if self.__metadata__was__set:
		bzz_dictionary["metadata"] = self.metadata
	if self.__operator__was__set:
		bzz_dictionary["operator"] = self.operator
	if self.__slug__was__set:
		bzz_dictionary["slug"] = self.slug
	if self.__sort_order__was__set:
		bzz_dictionary["sort_order"] = self.sort_order
	if self.__starts_at__was__set:
		bzz_dictionary["starts_at"] = self.starts_at
	if self.__title__was__set:
		bzz_dictionary["title"] = self.title
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("description"):
		me.description = from_dict["description"]
	if from_dict.has("ends_at"):
		me.ends_at = from_dict["ends_at"]
	if from_dict.has("metadata"):
		me.metadata = from_dict["metadata"]
	if from_dict.has("operator"):
		me.operator = from_dict["operator"]
	if from_dict.has("slug"):
		me.slug = from_dict["slug"]
	if from_dict.has("sort_order"):
		me.sort_order = from_dict["sort_order"]
	if from_dict.has("starts_at"):
		me.starts_at = from_dict["starts_at"]
	if from_dict.has("title"):
		me.title = from_dict["title"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

