extends Resource
class_name AdminUpdateUser200ResponseData

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# AdminUpdateUser200ResponseData Model


# Required: False
# isArray: false
@export var display_name: String = "":
	set(value):
		__display_name__was__set = true
		display_name = value
var __display_name__was__set := false

# Required: False
# isArray: false
@export var email: String = "":
	set(value):
		__email__was__set = true
		email = value
var __email__was__set := false

# Required: False
# isArray: false
@export var id: int:
	set(value):
		__id__was__set = true
		id = value
var __id__was__set := false

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var inserted_at: String:
	set(value):
		__inserted_at__was__set = true
		inserted_at = value
var __inserted_at__was__set := false

# Required: False
# isArray: false
@export var is_admin: bool:
	set(value):
		__is_admin__was__set = true
		is_admin = value
var __is_admin__was__set := false

# Required: False
# isArray: false
@export var lobby_id: int:
	set(value):
		__lobby_id__was__set = true
		lobby_id = value
var __lobby_id__was__set := false

# Required: False
# isArray: false
@export var metadata: Dictionary:
	set(value):
		__metadata__was__set = true
		metadata = value
var __metadata__was__set := false

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var updated_at: String:
	set(value):
		__updated_at__was__set = true
		updated_at = value
var __updated_at__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__display_name__was__set:
		bzz_dictionary["display_name"] = self.display_name
	if self.__email__was__set:
		bzz_dictionary["email"] = self.email
	if self.__id__was__set:
		bzz_dictionary["id"] = self.id
	if self.__inserted_at__was__set:
		bzz_dictionary["inserted_at"] = self.inserted_at
	if self.__is_admin__was__set:
		bzz_dictionary["is_admin"] = self.is_admin
	if self.__lobby_id__was__set:
		bzz_dictionary["lobby_id"] = self.lobby_id
	if self.__metadata__was__set:
		bzz_dictionary["metadata"] = self.metadata
	if self.__updated_at__was__set:
		bzz_dictionary["updated_at"] = self.updated_at
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("display_name"):
		me.display_name = from_dict["display_name"]
	if from_dict.has("email"):
		me.email = from_dict["email"]
	if from_dict.has("id"):
		me.id = from_dict["id"]
	if from_dict.has("inserted_at"):
		me.inserted_at = from_dict["inserted_at"]
	if from_dict.has("is_admin"):
		me.is_admin = from_dict["is_admin"]
	if from_dict.has("lobby_id"):
		me.lobby_id = from_dict["lobby_id"]
	if from_dict.has("metadata"):
		me.metadata = from_dict["metadata"]
	if from_dict.has("updated_at"):
		me.updated_at = from_dict["updated_at"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

