extends Resource
class_name CallHookRequest

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# CallHookRequest Model


# Required: False
# isArray: true
@export var args: Array:
	set(value):
		__args__was__set = true
		args = value
var __args__was__set := false

# Required: True
# isArray: false
@export var fn: String = "":
	set(value):
		__fn__was__set = true
		fn = value
var __fn__was__set := false

# Required: True
# isArray: false
@export var plugin: String = "":
	set(value):
		__plugin__was__set = true
		plugin = value
var __plugin__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	if not self.__fn__was__set:
		bzz_missing_properties.append("fn")
	if not self.__plugin__was__set:
		bzz_missing_properties.append("plugin")
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__args__was__set:
		bzz_dictionary["args"] = self.args
	if self.__fn__was__set:
		bzz_dictionary["fn"] = self.fn
	if self.__plugin__was__set:
		bzz_dictionary["plugin"] = self.plugin
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("args"):
		me.args = from_dict["args"]
	if from_dict.has("fn"):
		me.fn = from_dict["fn"]
	if from_dict.has("plugin"):
		me.plugin = from_dict["plugin"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

