extends Resource
class_name CancelJoinRequest200Response

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# CancelJoinRequest200Response Model


# Required: False
# isArray: false
@export var display_name: String = "":
	set(value):
		__display_name__was__set = true
		display_name = value
var __display_name__was__set := false

# Required: False
# isArray: false
@export var group_id: int:
	set(value):
		__group_id__was__set = true
		group_id = value
var __group_id__was__set := false

# Join request ID
# Required: False
# isArray: false
@export var id: int:
	set(value):
		__id__was__set = true
		id = value
var __id__was__set := false

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var inserted_at: String:
	set(value):
		__inserted_at__was__set = true
		inserted_at = value
var __inserted_at__was__set := false

# Required: False
# isArray: false
# Allowed values: "pending", "accepted", "rejected"
@export var status: String = "":
	set(value):
		if str(value) != "" and not (str(value) in __status__allowable__values):
			push_error("CancelJoinRequest200Response: tried to set property `status` to a value that is not allowed." +
				"  Allowed values: `pending`, `accepted`, `rejected`")
			return
		__status__was__set = true
		status = value
var __status__was__set := false
var __status__allowable__values := ["pending", "accepted", "rejected"]

# Required: False
# isArray: false
@export var user_id: int:
	set(value):
		__user_id__was__set = true
		user_id = value
var __user_id__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__display_name__was__set:
		bzz_dictionary["display_name"] = self.display_name
	if self.__group_id__was__set:
		bzz_dictionary["group_id"] = self.group_id
	if self.__id__was__set:
		bzz_dictionary["id"] = self.id
	if self.__inserted_at__was__set:
		bzz_dictionary["inserted_at"] = self.inserted_at
	if self.__status__was__set:
		bzz_dictionary["status"] = self.status
	if self.__user_id__was__set:
		bzz_dictionary["user_id"] = self.user_id
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("display_name"):
		me.display_name = from_dict["display_name"]
	if from_dict.has("group_id"):
		me.group_id = from_dict["group_id"]
	if from_dict.has("id"):
		me.id = from_dict["id"]
	if from_dict.has("inserted_at"):
		me.inserted_at = from_dict["inserted_at"]
	if from_dict.has("status"):
		me.status = from_dict["status"]
	if from_dict.has("user_id"):
		me.user_id = from_dict["user_id"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

