extends Resource
class_name CreateLobbyRequest

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# CreateLobbyRequest Model


# Hide from public listings
# Required: False
# isArray: false
@export var is_hidden: bool = false:
	set(value):
		__is_hidden__was__set = true
		is_hidden = value
var __is_hidden__was__set := false

# Lock the lobby
# Required: False
# isArray: false
@export var is_locked: bool = false:
	set(value):
		__is_locked__was__set = true
		is_locked = value
var __is_locked__was__set := false

# Maximum users allowed (default: 8)
# Required: False
# isArray: false
@export var max_users: int = 8:
	set(value):
		__max_users__was__set = true
		max_users = value
var __max_users__was__set := false

# Arbitrary metadata
# Required: False
# isArray: false
@export var metadata: Dictionary:
	set(value):
		__metadata__was__set = true
		metadata = value
var __metadata__was__set := false

# Optional password to protect the lobby
# Required: False
# isArray: false
@export var password: String = "":
	set(value):
		__password__was__set = true
		password = value
var __password__was__set := false

# Display title for the lobby
# Required: False
# isArray: false
@export var title: String = "":
	set(value):
		__title__was__set = true
		title = value
var __title__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__is_hidden__was__set:
		bzz_dictionary["is_hidden"] = self.is_hidden
	if self.__is_locked__was__set:
		bzz_dictionary["is_locked"] = self.is_locked
	if self.__max_users__was__set:
		bzz_dictionary["max_users"] = self.max_users
	if self.__metadata__was__set:
		bzz_dictionary["metadata"] = self.metadata
	if self.__password__was__set:
		bzz_dictionary["password"] = self.password
	if self.__title__was__set:
		bzz_dictionary["title"] = self.title
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("is_hidden"):
		me.is_hidden = from_dict["is_hidden"]
	if from_dict.has("is_locked"):
		me.is_locked = from_dict["is_locked"]
	if from_dict.has("max_users"):
		me.max_users = from_dict["max_users"]
	if from_dict.has("metadata"):
		me.metadata = from_dict["metadata"]
	if from_dict.has("password"):
		me.password = from_dict["password"]
	if from_dict.has("title"):
		me.title = from_dict["title"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

