extends Resource
class_name GetCurrentUser200ResponseLinkedProviders

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# GetCurrentUser200ResponseLinkedProviders Model
# Shows which OAuth providers are linked to this account


# Required: False
# isArray: false
@export var apple: bool:
	set(value):
		__apple__was__set = true
		apple = value
var __apple__was__set := false

# Required: False
# isArray: false
@export var device: bool:
	set(value):
		__device__was__set = true
		device = value
var __device__was__set := false

# Required: False
# isArray: false
@export var discord: bool:
	set(value):
		__discord__was__set = true
		discord = value
var __discord__was__set := false

# Required: False
# isArray: false
@export var facebook: bool:
	set(value):
		__facebook__was__set = true
		facebook = value
var __facebook__was__set := false

# Required: False
# isArray: false
@export var google: bool:
	set(value):
		__google__was__set = true
		google = value
var __google__was__set := false

# Required: False
# isArray: false
@export var steam: bool:
	set(value):
		__steam__was__set = true
		steam = value
var __steam__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__apple__was__set:
		bzz_dictionary["apple"] = self.apple
	if self.__device__was__set:
		bzz_dictionary["device"] = self.device
	if self.__discord__was__set:
		bzz_dictionary["discord"] = self.discord
	if self.__facebook__was__set:
		bzz_dictionary["facebook"] = self.facebook
	if self.__google__was__set:
		bzz_dictionary["google"] = self.google
	if self.__steam__was__set:
		bzz_dictionary["steam"] = self.steam
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("apple"):
		me.apple = from_dict["apple"]
	if from_dict.has("device"):
		me.device = from_dict["device"]
	if from_dict.has("discord"):
		me.discord = from_dict["discord"]
	if from_dict.has("facebook"):
		me.facebook = from_dict["facebook"]
	if from_dict.has("google"):
		me.google = from_dict["google"]
	if from_dict.has("steam"):
		me.steam = from_dict["steam"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

