extends Resource
class_name GetLobby200Response

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# GetLobby200Response Model


# Required: False
# isArray: false
@export var data: ListLobbies200ResponseDataInner:
	set(value):
		__data__was__set = true
		data = value
var __data__was__set := false

# Required: False
# isArray: true
@export var members: Array:
	set(value):
		__members__was__set = true
		members = value
var __members__was__set := false

# Number of current spectators
# Required: False
# isArray: false
@export var spectator_count: int:
	set(value):
		__spectator_count__was__set = true
		spectator_count = value
var __spectator_count__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__data__was__set:
		bzz_dictionary["data"] = self.data
	if self.__members__was__set:
		bzz_dictionary["members"] = self.members
	if self.__spectator_count__was__set:
		bzz_dictionary["spectator_count"] = self.spectator_count
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("data"):
		me.data = ListLobbies200ResponseDataInner.bzz_denormalize_single(from_dict["data"])
	if from_dict.has("members"):
		me.members = GetLobby200ResponseMembersInner.bzz_denormalize_multiple(from_dict["members"])
	if from_dict.has("spectator_count"):
		me.spectator_count = from_dict["spectator_count"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes
