extends Resource
class_name HealthResponse

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# HealthResponse Model
# Response from health check endpoint


# Health status
# Required: True
# Example: ok
# isArray: false
@export var status: String = "":
	set(value):
		__status__was__set = true
		status = value
var __status__was__set := false

# Current timestamp
# Required: True
# Example: 2025-11-22T16:00:00Z
# isArray: false
@export var timestamp: String = "":
	set(value):
		__timestamp__was__set = true
		timestamp = value
var __timestamp__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	if not self.__status__was__set:
		bzz_missing_properties.append("status")
	if not self.__timestamp__was__set:
		bzz_missing_properties.append("timestamp")
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__status__was__set:
		bzz_dictionary["status"] = self.status
	if self.__timestamp__was__set:
		bzz_dictionary["timestamp"] = self.timestamp
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("status"):
		me.status = from_dict["status"]
	if from_dict.has("timestamp"):
		me.timestamp = from_dict["timestamp"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

