extends Resource
class_name ListLobbies200ResponseInner

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# ListLobbies200ResponseInner Model


# User ID of the host
# Required: False
# isArray: false
@export var host_id: int:
	set(value):
		__host_id__was__set = true
		host_id = value
var __host_id__was__set := false

# Whether this is a server-managed lobby
# Required: False
# isArray: false
@export var hostless: bool:
	set(value):
		__hostless__was__set = true
		hostless = value
var __hostless__was__set := false

# Lobby ID
# Required: False
# isArray: false
@export var id: int:
	set(value):
		__id__was__set = true
		id = value
var __id__was__set := false

# Hidden from public listings
# Required: False
# isArray: false
@export var is_hidden: bool:
	set(value):
		__is_hidden__was__set = true
		is_hidden = value
var __is_hidden__was__set := false

# Locked - no new joins allowed
# Required: False
# isArray: false
@export var is_locked: bool:
	set(value):
		__is_locked__was__set = true
		is_locked = value
var __is_locked__was__set := false

# Maximum number of users allowed
# Required: False
# isArray: false
@export var max_users: int:
	set(value):
		__max_users__was__set = true
		max_users = value
var __max_users__was__set := false

# Arbitrary metadata
# Required: False
# isArray: false
@export var metadata: Dictionary:
	set(value):
		__metadata__was__set = true
		metadata = value
var __metadata__was__set := false

# Unique slug identifier
# Required: False
# isArray: false
@export var name: String = "":
	set(value):
		__name__was__set = true
		name = value
var __name__was__set := false

# Display title
# Required: False
# isArray: false
@export var title: String = "":
	set(value):
		__title__was__set = true
		title = value
var __title__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__host_id__was__set:
		bzz_dictionary["host_id"] = self.host_id
	if self.__hostless__was__set:
		bzz_dictionary["hostless"] = self.hostless
	if self.__id__was__set:
		bzz_dictionary["id"] = self.id
	if self.__is_hidden__was__set:
		bzz_dictionary["is_hidden"] = self.is_hidden
	if self.__is_locked__was__set:
		bzz_dictionary["is_locked"] = self.is_locked
	if self.__max_users__was__set:
		bzz_dictionary["max_users"] = self.max_users
	if self.__metadata__was__set:
		bzz_dictionary["metadata"] = self.metadata
	if self.__name__was__set:
		bzz_dictionary["name"] = self.name
	if self.__title__was__set:
		bzz_dictionary["title"] = self.title
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("host_id"):
		me.host_id = from_dict["host_id"]
	if from_dict.has("hostless"):
		me.hostless = from_dict["hostless"]
	if from_dict.has("id"):
		me.id = from_dict["id"]
	if from_dict.has("is_hidden"):
		me.is_hidden = from_dict["is_hidden"]
	if from_dict.has("is_locked"):
		me.is_locked = from_dict["is_locked"]
	if from_dict.has("max_users"):
		me.max_users = from_dict["max_users"]
	if from_dict.has("metadata"):
		me.metadata = from_dict["metadata"]
	if from_dict.has("name"):
		me.name = from_dict["name"]
	if from_dict.has("title"):
		me.title = from_dict["title"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

