extends Resource
class_name ListLeaderboardRecords200ResponseMeta

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# ListLeaderboardRecords200ResponseMeta Model


# Required: False
# isArray: false
@export var count: int:
	set(value):
		__count__was__set = true
		count = value
var __count__was__set := false

# Required: False
# isArray: false
@export var has_more: bool:
	set(value):
		__has_more__was__set = true
		has_more = value
var __has_more__was__set := false

# Required: False
# isArray: false
@export var page: int:
	set(value):
		__page__was__set = true
		page = value
var __page__was__set := false

# Required: False
# isArray: false
@export var page_size: int:
	set(value):
		__page_size__was__set = true
		page_size = value
var __page_size__was__set := false

# Required: False
# isArray: false
@export var total_count: int:
	set(value):
		__total_count__was__set = true
		total_count = value
var __total_count__was__set := false

# Required: False
# isArray: false
@export var total_pages: int:
	set(value):
		__total_pages__was__set = true
		total_pages = value
var __total_pages__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__count__was__set:
		bzz_dictionary["count"] = self.count
	if self.__has_more__was__set:
		bzz_dictionary["has_more"] = self.has_more
	if self.__page__was__set:
		bzz_dictionary["page"] = self.page
	if self.__page_size__was__set:
		bzz_dictionary["page_size"] = self.page_size
	if self.__total_count__was__set:
		bzz_dictionary["total_count"] = self.total_count
	if self.__total_pages__was__set:
		bzz_dictionary["total_pages"] = self.total_pages
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("count"):
		me.count = from_dict["count"]
	if from_dict.has("has_more"):
		me.has_more = from_dict["has_more"]
	if from_dict.has("page"):
		me.page = from_dict["page"]
	if from_dict.has("page_size"):
		me.page_size = from_dict["page_size"]
	if from_dict.has("total_count"):
		me.total_count = from_dict["total_count"]
	if from_dict.has("total_pages"):
		me.total_pages = from_dict["total_pages"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes
