extends Resource
class_name ListGroupMembers200ResponseDataInner

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# ListGroupMembers200ResponseDataInner Model


# Required: False
# isArray: false
@export var display_name: String = "":
	set(value):
		__display_name__was__set = true
		display_name = value
var __display_name__was__set := false

# Required: False
# isArray: false
@export var group_id: int:
	set(value):
		__group_id__was__set = true
		group_id = value
var __group_id__was__set := false

# Membership ID
# Required: False
# isArray: false
@export var id: int:
	set(value):
		__id__was__set = true
		id = value
var __id__was__set := false

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var inserted_at: String:
	set(value):
		__inserted_at__was__set = true
		inserted_at = value
var __inserted_at__was__set := false

# Required: False
# isArray: false
@export var is_online: bool:
	set(value):
		__is_online__was__set = true
		is_online = value
var __is_online__was__set := false

#       (but it's actually a DateTime ; no timezones support in Gdscript)
# Required: False
# isArray: false
@export var last_seen_at: String:
	set(value):
		__last_seen_at__was__set = true
		last_seen_at = value
var __last_seen_at__was__set := false

# Required: False
# isArray: false
@export var profile_url: String = "":
	set(value):
		__profile_url__was__set = true
		profile_url = value
var __profile_url__was__set := false

# Required: False
# isArray: false
# Allowed values: "admin", "member"
@export var role: String = "":
	set(value):
		if str(value) != "" and not (str(value) in __role__allowable__values):
			push_error("ListGroupMembers200ResponseDataInner: tried to set property `role` to a value that is not allowed." +
				"  Allowed values: `admin`, `member`")
			return
		__role__was__set = true
		role = value
var __role__was__set := false
var __role__allowable__values := ["admin", "member"]

# Required: False
# isArray: false
@export var user_id: int:
	set(value):
		__user_id__was__set = true
		user_id = value
var __user_id__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__display_name__was__set:
		bzz_dictionary["display_name"] = self.display_name
	if self.__group_id__was__set:
		bzz_dictionary["group_id"] = self.group_id
	if self.__id__was__set:
		bzz_dictionary["id"] = self.id
	if self.__inserted_at__was__set:
		bzz_dictionary["inserted_at"] = self.inserted_at
	if self.__is_online__was__set:
		bzz_dictionary["is_online"] = self.is_online
	if self.__last_seen_at__was__set:
		bzz_dictionary["last_seen_at"] = self.last_seen_at
	if self.__profile_url__was__set:
		bzz_dictionary["profile_url"] = self.profile_url
	if self.__role__was__set:
		bzz_dictionary["role"] = self.role
	if self.__user_id__was__set:
		bzz_dictionary["user_id"] = self.user_id
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("display_name"):
		me.display_name = from_dict["display_name"]
	if from_dict.has("group_id"):
		me.group_id = from_dict["group_id"]
	if from_dict.has("id"):
		me.id = from_dict["id"]
	if from_dict.has("inserted_at"):
		me.inserted_at = from_dict["inserted_at"]
	if from_dict.has("is_online"):
		me.is_online = from_dict["is_online"]
	if from_dict.has("last_seen_at"):
		me.last_seen_at = from_dict["last_seen_at"]
	if from_dict.has("profile_url"):
		me.profile_url = from_dict["profile_url"]
	if from_dict.has("role"):
		me.role = from_dict["role"]
	if from_dict.has("user_id"):
		me.user_id = from_dict["user_id"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

