extends Resource
class_name ListFriendRequests200ResponseIncomingInner

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# ListFriendRequests200ResponseIncomingInner Model


# Required: False
# isArray: false
@export var id: int:
	set(value):
		__id__was__set = true
		id = value
var __id__was__set := false

# Required: False
# isArray: false
@export var inserted_at: String = "":
	set(value):
		__inserted_at__was__set = true
		inserted_at = value
var __inserted_at__was__set := false

# Required: False
# isArray: false
@export var requester: ListFriendRequests200ResponseIncomingInnerRequester:
	set(value):
		__requester__was__set = true
		requester = value
var __requester__was__set := false

# Required: False
# isArray: false
@export var status: String = "":
	set(value):
		__status__was__set = true
		status = value
var __status__was__set := false

# Required: False
# isArray: false
@export var target: ListFriendRequests200ResponseIncomingInnerRequester:
	set(value):
		__target__was__set = true
		target = value
var __target__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__id__was__set:
		bzz_dictionary["id"] = self.id
	if self.__inserted_at__was__set:
		bzz_dictionary["inserted_at"] = self.inserted_at
	if self.__requester__was__set:
		bzz_dictionary["requester"] = self.requester
	if self.__status__was__set:
		bzz_dictionary["status"] = self.status
	if self.__target__was__set:
		bzz_dictionary["target"] = self.target
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("id"):
		me.id = from_dict["id"]
	if from_dict.has("inserted_at"):
		me.inserted_at = from_dict["inserted_at"]
	if from_dict.has("requester"):
		me.requester = ListFriendRequests200ResponseIncomingInnerRequester.bzz_denormalize_single(from_dict["requester"])
	if from_dict.has("status"):
		me.status = from_dict["status"]
	if from_dict.has("target"):
		me.target = ListFriendRequests200ResponseIncomingInnerRequester.bzz_denormalize_single(from_dict["target"])
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

