extends Resource
class_name OAuthSessionData

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# OAuthSessionData Model
# Payload stored on completed or errored OAuth sessions


# Short-lived access token
# Required: False
# isArray: false
@export var access_token: String = "":
	set(value):
		__access_token__was__set = true
		access_token = value
var __access_token__was__set := false

# Required: False
# isArray: false
@export var details: OAuthSessionDataDetails:
	set(value):
		__details__was__set = true
		details = value
var __details__was__set := false

# Seconds until access_token expires
# Required: False
# isArray: false
@export var expires_in: int:
	set(value):
		__expires_in__was__set = true
		expires_in = value
var __expires_in__was__set := false

# Long-lived refresh token
# Required: False
# isArray: false
@export var refresh_token: String = "":
	set(value):
		__refresh_token__was__set = true
		refresh_token = value
var __refresh_token__was__set := false

# User id that was authenticated for this session (when completed)
# Required: False
# isArray: false
@export var user_id: int:
	set(value):
		__user_id__was__set = true
		user_id = value
var __user_id__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__access_token__was__set:
		bzz_dictionary["access_token"] = self.access_token
	if self.__details__was__set:
		bzz_dictionary["details"] = self.details
	if self.__expires_in__was__set:
		bzz_dictionary["expires_in"] = self.expires_in
	if self.__refresh_token__was__set:
		bzz_dictionary["refresh_token"] = self.refresh_token
	if self.__user_id__was__set:
		bzz_dictionary["user_id"] = self.user_id
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("access_token"):
		me.access_token = from_dict["access_token"]
	if from_dict.has("details"):
		me.details = OAuthSessionDataDetails.bzz_denormalize_single(from_dict["details"])
	if from_dict.has("expires_in"):
		me.expires_in = from_dict["expires_in"]
	if from_dict.has("refresh_token"):
		me.refresh_token = from_dict["refresh_token"]
	if from_dict.has("user_id"):
		me.user_id = from_dict["user_id"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

