extends Resource
class_name OauthGoogleIdTokenRequest

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# OauthGoogleIdTokenRequest Model


# Google OpenID Connect id_token JWT. Audience must match GOOGLE_WEB_CLIENT_ID or GOOGLE_CLIENT_ID.
# Required: True
# isArray: false
@export var id_token: String = "":
	set(value):
		__id_token__was__set = true
		id_token = value
var __id_token__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	if not self.__id_token__was__set:
		bzz_missing_properties.append("id_token")
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__id_token__was__set:
		bzz_dictionary["id_token"] = self.id_token
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("id_token"):
		me.id_token = from_dict["id_token"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

