extends Resource
class_name OauthRequest200Response

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# OauthRequest200Response Model


# URL to redirect user to for OAuth
# Required: False
# isArray: false
@export var authorization_url: String = "":
	set(value):
		__authorization_url__was__set = true
		authorization_url = value
var __authorization_url__was__set := false

# Unique session ID to track this OAuth request
# Required: False
# isArray: false
@export var session_id: String = "":
	set(value):
		__session_id__was__set = true
		session_id = value
var __session_id__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__authorization_url__was__set:
		bzz_dictionary["authorization_url"] = self.authorization_url
	if self.__session_id__was__set:
		bzz_dictionary["session_id"] = self.session_id
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("authorization_url"):
		me.authorization_url = from_dict["authorization_url"]
	if from_dict.has("session_id"):
		me.session_id = from_dict["session_id"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

