extends Resource
class_name SearchUsers200ResponseDataInner

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# SearchUsers200ResponseDataInner Model


# Required: False
# isArray: false
@export var display_name: String = "":
	set(value):
		__display_name__was__set = true
		display_name = value
var __display_name__was__set := false

# Required: False
# isArray: false
@export var email: String = "":
	set(value):
		__email__was__set = true
		email = value
var __email__was__set := false

# Required: False
# isArray: false
@export var id: int:
	set(value):
		__id__was__set = true
		id = value
var __id__was__set := false

# Lobby ID when user is currently in a lobby. -1 means not currently in a lobby.
# Required: False
# isArray: false
@export var lobby_id: int:
	set(value):
		__lobby_id__was__set = true
		lobby_id = value
var __lobby_id__was__set := false

# Required: False
# isArray: false
@export var profile_url: String = "":
	set(value):
		__profile_url__was__set = true
		profile_url = value
var __profile_url__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__display_name__was__set:
		bzz_dictionary["display_name"] = self.display_name
	if self.__email__was__set:
		bzz_dictionary["email"] = self.email
	if self.__id__was__set:
		bzz_dictionary["id"] = self.id
	if self.__lobby_id__was__set:
		bzz_dictionary["lobby_id"] = self.lobby_id
	if self.__profile_url__was__set:
		bzz_dictionary["profile_url"] = self.profile_url
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("display_name"):
		me.display_name = from_dict["display_name"]
	if from_dict.has("email"):
		me.email = from_dict["email"]
	if from_dict.has("id"):
		me.id = from_dict["id"]
	if from_dict.has("lobby_id"):
		me.lobby_id = from_dict["lobby_id"]
	if from_dict.has("profile_url"):
		me.profile_url = from_dict["profile_url"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

