extends Resource
class_name SendNotificationRequest

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# SendNotificationRequest Model


# Notification body text (optional)
# Required: False
# isArray: false
@export var content: String = "":
	set(value):
		__content__was__set = true
		content = value
var __content__was__set := false

# Arbitrary metadata (optional)
# Required: False
# isArray: false
@export var metadata: Dictionary:
	set(value):
		__metadata__was__set = true
		metadata = value
var __metadata__was__set := false

# Notification title (required)
# Required: True
# isArray: false
@export var title: String = "":
	set(value):
		__title__was__set = true
		title = value
var __title__was__set := false

# Recipient user ID (must be an accepted friend)
# Required: True
# isArray: false
@export var user_id: int:
	set(value):
		__user_id__was__set = true
		user_id = value
var __user_id__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	if not self.__title__was__set:
		bzz_missing_properties.append("title")
	if not self.__user_id__was__set:
		bzz_missing_properties.append("user_id")
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__content__was__set:
		bzz_dictionary["content"] = self.content
	if self.__metadata__was__set:
		bzz_dictionary["metadata"] = self.metadata
	if self.__title__was__set:
		bzz_dictionary["title"] = self.title
	if self.__user_id__was__set:
		bzz_dictionary["user_id"] = self.user_id
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("content"):
		me.content = from_dict["content"]
	if from_dict.has("metadata"):
		me.metadata = from_dict["metadata"]
	if from_dict.has("title"):
		me.title = from_dict["title"]
	if from_dict.has("user_id"):
		me.user_id = from_dict["user_id"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes
