extends Resource
class_name SendChatMessageRequest

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# SendChatMessageRequest Model


# Reference ID (lobby_id, group_id, party_id, or friend user_id)
# Required: True
# isArray: false
@export var chat_ref_id: int:
	set(value):
		__chat_ref_id__was__set = true
		chat_ref_id = value
var __chat_ref_id__was__set := false

# Type of chat
# Required: True
# isArray: false
# Allowed values: "lobby", "group", "friend", "party"
@export var chat_type: String = "":
	set(value):
		if str(value) != "" and not (str(value) in __chat_type__allowable__values):
			push_error("SendChatMessageRequest: tried to set property `chat_type` to a value that is not allowed." +
				"  Allowed values: `lobby`, `group`, `friend`, `party`")
			return
		__chat_type__was__set = true
		chat_type = value
var __chat_type__was__set := false
var __chat_type__allowable__values := ["lobby", "group", "friend", "party"]

# Message text (1-4096 chars)
# Required: True
# isArray: false
@export var content: String = "":
	set(value):
		__content__was__set = true
		content = value
var __content__was__set := false

# Optional metadata
# Required: False
# isArray: false
@export var metadata: Dictionary:
	set(value):
		__metadata__was__set = true
		metadata = value
var __metadata__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	if not self.__chat_ref_id__was__set:
		bzz_missing_properties.append("chat_ref_id")
	if not self.__chat_type__was__set:
		bzz_missing_properties.append("chat_type")
	if not self.__content__was__set:
		bzz_missing_properties.append("content")
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__chat_ref_id__was__set:
		bzz_dictionary["chat_ref_id"] = self.chat_ref_id
	if self.__chat_type__was__set:
		bzz_dictionary["chat_type"] = self.chat_type
	if self.__content__was__set:
		bzz_dictionary["content"] = self.content
	if self.__metadata__was__set:
		bzz_dictionary["metadata"] = self.metadata
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("chat_ref_id"):
		me.chat_ref_id = from_dict["chat_ref_id"]
	if from_dict.has("chat_type"):
		me.chat_type = from_dict["chat_type"]
	if from_dict.has("content"):
		me.content = from_dict["content"]
	if from_dict.has("metadata"):
		me.metadata = from_dict["metadata"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

