extends Resource
class_name ShowParty200Response

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# ShowParty200Response Model


# Unique 6-character code for joining the party
# Required: False
# isArray: false
@export var code: String = "":
	set(value):
		__code__was__set = true
		code = value
var __code__was__set := false

# Party ID
# Required: False
# isArray: false
@export var id: int:
	set(value):
		__id__was__set = true
		id = value
var __id__was__set := false

# User ID of the party leader
# Required: False
# isArray: false
@export var leader_id: int:
	set(value):
		__leader_id__was__set = true
		leader_id = value
var __leader_id__was__set := false

# Maximum party members allowed
# Required: False
# isArray: false
@export var max_size: int:
	set(value):
		__max_size__was__set = true
		max_size = value
var __max_size__was__set := false

# Current party members
# Required: False
# isArray: true
@export var members: Array:
	set(value):
		__members__was__set = true
		members = value
var __members__was__set := false

# Arbitrary metadata
# Required: False
# isArray: false
@export var metadata: Dictionary:
	set(value):
		__metadata__was__set = true
		metadata = value
var __metadata__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__code__was__set:
		bzz_dictionary["code"] = self.code
	if self.__id__was__set:
		bzz_dictionary["id"] = self.id
	if self.__leader_id__was__set:
		bzz_dictionary["leader_id"] = self.leader_id
	if self.__max_size__was__set:
		bzz_dictionary["max_size"] = self.max_size
	if self.__members__was__set:
		bzz_dictionary["members"] = self.members
	if self.__metadata__was__set:
		bzz_dictionary["metadata"] = self.metadata
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("code"):
		me.code = from_dict["code"]
	if from_dict.has("id"):
		me.id = from_dict["id"]
	if from_dict.has("leader_id"):
		me.leader_id = from_dict["leader_id"]
	if from_dict.has("max_size"):
		me.max_size = from_dict["max_size"]
	if from_dict.has("members"):
		me.members = ShowParty200ResponseMembersInner.bzz_denormalize_multiple(from_dict["members"])
	if from_dict.has("metadata"):
		me.metadata = from_dict["metadata"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes
