extends Resource
class_name UpdateGroupRequest

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# UpdateGroupRequest Model


# Required: False
# isArray: false
@export var description: String = "":
	set(value):
		__description__was__set = true
		description = value
var __description__was__set := false

# Required: False
# isArray: false
@export var max_members: int:
	set(value):
		__max_members__was__set = true
		max_members = value
var __max_members__was__set := false

# Required: False
# isArray: false
@export var metadata: Dictionary:
	set(value):
		__metadata__was__set = true
		metadata = value
var __metadata__was__set := false

# Chat slowdown in seconds (0 = disabled, max 3600)
# Required: False
# isArray: false
@export var slowdown: int:
	set(value):
		__slowdown__was__set = true
		slowdown = value
var __slowdown__was__set := false

# Required: False
# isArray: false
@export var title: String = "":
	set(value):
		__title__was__set = true
		title = value
var __title__was__set := false

# Required: False
# isArray: false
# Allowed values: "public", "private", "hidden"
@export var type: String = "":
	set(value):
		if str(value) != "" and not (str(value) in __type__allowable__values):
			push_error("UpdateGroupRequest: tried to set property `type` to a value that is not allowed." +
				"  Allowed values: `public`, `private`, `hidden`")
			return
		__type__was__set = true
		type = value
var __type__was__set := false
var __type__allowable__values := ["public", "private", "hidden"]


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__description__was__set:
		bzz_dictionary["description"] = self.description
	if self.__max_members__was__set:
		bzz_dictionary["max_members"] = self.max_members
	if self.__metadata__was__set:
		bzz_dictionary["metadata"] = self.metadata
	if self.__slowdown__was__set:
		bzz_dictionary["slowdown"] = self.slowdown
	if self.__title__was__set:
		bzz_dictionary["title"] = self.title
	if self.__type__was__set:
		bzz_dictionary["type"] = self.type
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("description"):
		me.description = from_dict["description"]
	if from_dict.has("max_members"):
		me.max_members = from_dict["max_members"]
	if from_dict.has("metadata"):
		me.metadata = from_dict["metadata"]
	if from_dict.has("slowdown"):
		me.slowdown = from_dict["slowdown"]
	if from_dict.has("title"):
		me.title = from_dict["title"]
	if from_dict.has("type"):
		me.type = from_dict["type"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

