extends ApiApiBeeClient
class_name AdminChatApi

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# API AdminChatApi
# Instantiate this object and use it to make requests to the API.

func _bzz_get_api_name() -> String:
	return "AdminChatApi"


# Operation adminDeleteChatConversation → DELETE /api/v1/admin/chat/conversation
# Delete all messages in a conversation (admin)
#
# Delete all messages for a given chat_type and chat_ref_id.
func admin_delete_chat_conversation(
	# chatType: String = ""   Eg: chatType_example
	chatType: String,
	# chatRefId: int   Eg: 56
	chatRefId: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("DELETE")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/chat/conversation"

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()
	bzz_query["chat_type"] = chatType
	bzz_query["chat_ref_id"] = chatRefId

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = AdminDeleteChatConversation200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_delete_chat_conversation_threaded(
	# chatType: String = ""   Eg: chatType_example
	chatType: String,
	# chatRefId: int   Eg: 56
	chatRefId: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_delete_chat_conversation")
	bzz_callable.bind(
		chatType,
		chatRefId,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation adminDeleteChatMessage → DELETE /api/v1/admin/chat/{id}
# Delete a chat message (admin)
#
# Admin-level message deletion by ID.
func admin_delete_chat_message(
	# id: int   Eg: 56
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("DELETE")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/chat/{id}".replace("{" + "id" + "}", _bzz_urlize_path_param(id))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_delete_chat_message_threaded(
	# id: int   Eg: 56
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_delete_chat_message")
	bzz_callable.bind(
		id,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation adminListChatMessages → GET /api/v1/admin/chat
# List all chat messages (admin)
#
# List all chat messages with optional filters. Returns paginated results sorted by newest first.
func admin_list_chat_messages(
	# senderId: int   Eg: 56
	senderId = null,
	# chatType: String = ""   Eg: chatType_example
	chatType = "",
	# chatRefId: int   Eg: 56
	chatRefId = null,
	# content: String = ""   Eg: content_example
	content = "",
	# sortBy: String = ""   Eg: sortBy_example
	sortBy = "",
	# page: int   Eg: 56
	page = null,
	# pageSize: int   Eg: 56
	pageSize = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("GET")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/chat"

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()
	bzz_query["sender_id"] = senderId
	bzz_query["chat_type"] = chatType
	bzz_query["chat_ref_id"] = chatRefId
	bzz_query["content"] = content
	bzz_query["sort_by"] = sortBy
	bzz_query["page"] = page
	bzz_query["page_size"] = pageSize

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = AdminListChatMessages200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_list_chat_messages_threaded(
	# senderId: int   Eg: 56
	senderId = null,
	# chatType: String = ""   Eg: chatType_example
	chatType = "",
	# chatRefId: int   Eg: 56
	chatRefId = null,
	# content: String = ""   Eg: content_example
	content = "",
	# sortBy: String = ""   Eg: sortBy_example
	sortBy = "",
	# page: int   Eg: 56
	page = null,
	# pageSize: int   Eg: 56
	pageSize = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_list_chat_messages")
	bzz_callable.bind(
		senderId,
		chatType,
		chatRefId,
		content,
		sortBy,
		page,
		pageSize,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


