extends ApiApiBeeClient
class_name AdminPluginsApi

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# API AdminPluginsApi
# Instantiate this object and use it to make requests to the API.

func _bzz_get_api_name() -> String:
	return "AdminPluginsApi"


# Operation adminPluginsBuild → POST /api/v1/admin/plugins/build
# Build plugin bundle (admin)
func admin_plugins_build(
	# adminPluginsBuildRequest: AdminPluginsBuildRequest
	# Build request
	adminPluginsBuildRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("POST")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/plugins/build"

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_consumable_by_server := ['application/json']
	var bzz_found_producible_mime := false
	for bzz_mime in BZZ_PRODUCIBLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_consumable_by_server:
			bzz_headers["Content-Type"] = bzz_mime
			bzz_found_producible_mime = true
			break
	if not bzz_found_producible_mime:
		var error := ApiApiErrorClient.new()
		error.identifier = "admin_plugins_build.headers.content_type"
		error.message = "That endpoint only accepts %s as content type(s) and none are supported by this client."
		on_failure.call(error)
		return
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null
	bzz_body = adminPluginsBuildRequest

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_plugins_build_threaded(
	# adminPluginsBuildRequest: AdminPluginsBuildRequest
	# Build request
	adminPluginsBuildRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_plugins_build")
	bzz_callable.bind(
		adminPluginsBuildRequest,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation adminPluginsBuildable → GET /api/v1/admin/plugins/buildable
# List buildable plugin sources (admin)
func admin_plugins_buildable(
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("GET")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/plugins/buildable"

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_plugins_buildable_threaded(
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_plugins_buildable")
	bzz_callable.bind(
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation adminPluginsReload → POST /api/v1/admin/plugins/reload
# Reload hook plugins (admin)
func admin_plugins_reload(
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("POST")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/plugins/reload"

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_plugins_reload_threaded(
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_plugins_reload")
	bzz_callable.bind(
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


