extends ApiApiBeeClient
class_name AdminLeaderboardsApi

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# API AdminLeaderboardsApi
# Instantiate this object and use it to make requests to the API.

func _bzz_get_api_name() -> String:
	return "AdminLeaderboardsApi"


# Operation adminCreateLeaderboard → POST /api/v1/admin/leaderboards
# Create leaderboard (admin)
func admin_create_leaderboard(
	# adminCreateLeaderboardRequest: AdminCreateLeaderboardRequest
	# Leaderboard
	adminCreateLeaderboardRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("POST")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/leaderboards"

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_consumable_by_server := ['application/json']
	var bzz_found_producible_mime := false
	for bzz_mime in BZZ_PRODUCIBLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_consumable_by_server:
			bzz_headers["Content-Type"] = bzz_mime
			bzz_found_producible_mime = true
			break
	if not bzz_found_producible_mime:
		var error := ApiApiErrorClient.new()
		error.identifier = "admin_create_leaderboard.headers.content_type"
		error.message = "That endpoint only accepts %s as content type(s) and none are supported by this client."
		on_failure.call(error)
		return
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null
	bzz_body = adminCreateLeaderboardRequest

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = AdminEndLeaderboard200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_create_leaderboard_threaded(
	# adminCreateLeaderboardRequest: AdminCreateLeaderboardRequest
	# Leaderboard
	adminCreateLeaderboardRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_create_leaderboard")
	bzz_callable.bind(
		adminCreateLeaderboardRequest,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation adminDeleteLeaderboard → DELETE /api/v1/admin/leaderboards/{id}
# Delete leaderboard (admin)
func admin_delete_leaderboard(
	# id: int   Eg: 56
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("DELETE")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/leaderboards/{id}".replace("{" + "id" + "}", _bzz_urlize_path_param(id))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_delete_leaderboard_threaded(
	# id: int   Eg: 56
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_delete_leaderboard")
	bzz_callable.bind(
		id,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation adminDeleteLeaderboardRecord → DELETE /api/v1/admin/leaderboards/{id}/records/{record_id}
# Delete leaderboard record (admin)
func admin_delete_leaderboard_record(
	# id: int   Eg: 56
	id: int,
	# recordId: int   Eg: 56
	recordId: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("DELETE")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/leaderboards/{id}/records/{record_id}".replace("{" + "id" + "}", _bzz_urlize_path_param(id)).replace("{" + "record_id" + "}", _bzz_urlize_path_param(recordId))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_delete_leaderboard_record_threaded(
	# id: int   Eg: 56
	id: int,
	# recordId: int   Eg: 56
	recordId: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_delete_leaderboard_record")
	bzz_callable.bind(
		id,
		recordId,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation adminDeleteLeaderboardUserRecord → DELETE /api/v1/admin/leaderboards/{id}/records/user/{user_id}
# Delete a user's record (admin)
func admin_delete_leaderboard_user_record(
	# id: int   Eg: 56
	id: int,
	# userId: int   Eg: 56
	userId: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("DELETE")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/leaderboards/{id}/records/user/{user_id}".replace("{" + "id" + "}", _bzz_urlize_path_param(id)).replace("{" + "user_id" + "}", _bzz_urlize_path_param(userId))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_delete_leaderboard_user_record_threaded(
	# id: int   Eg: 56
	id: int,
	# userId: int   Eg: 56
	userId: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_delete_leaderboard_user_record")
	bzz_callable.bind(
		id,
		userId,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation adminEndLeaderboard → POST /api/v1/admin/leaderboards/{id}/end
# End leaderboard (admin)
func admin_end_leaderboard(
	# id: int   Eg: 56
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("POST")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/leaderboards/{id}/end".replace("{" + "id" + "}", _bzz_urlize_path_param(id))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = AdminEndLeaderboard200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_end_leaderboard_threaded(
	# id: int   Eg: 56
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_end_leaderboard")
	bzz_callable.bind(
		id,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation adminSubmitLeaderboardScore → POST /api/v1/admin/leaderboards/{id}/records
# Submit score (admin)
func admin_submit_leaderboard_score(
	# id: int   Eg: 56
	id: int,
	# adminSubmitLeaderboardScoreRequest: AdminSubmitLeaderboardScoreRequest
	# Score submission
	adminSubmitLeaderboardScoreRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("POST")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/leaderboards/{id}/records".replace("{" + "id" + "}", _bzz_urlize_path_param(id))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_consumable_by_server := ['application/json']
	var bzz_found_producible_mime := false
	for bzz_mime in BZZ_PRODUCIBLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_consumable_by_server:
			bzz_headers["Content-Type"] = bzz_mime
			bzz_found_producible_mime = true
			break
	if not bzz_found_producible_mime:
		var error := ApiApiErrorClient.new()
		error.identifier = "admin_submit_leaderboard_score.headers.content_type"
		error.message = "That endpoint only accepts %s as content type(s) and none are supported by this client."
		on_failure.call(error)
		return
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null
	bzz_body = adminSubmitLeaderboardScoreRequest

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = AdminSubmitLeaderboardScore200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_submit_leaderboard_score_threaded(
	# id: int   Eg: 56
	id: int,
	# adminSubmitLeaderboardScoreRequest: AdminSubmitLeaderboardScoreRequest
	# Score submission
	adminSubmitLeaderboardScoreRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_submit_leaderboard_score")
	bzz_callable.bind(
		id,
		adminSubmitLeaderboardScoreRequest,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation adminUpdateLeaderboard → PATCH /api/v1/admin/leaderboards/{id}
# Update leaderboard (admin)
func admin_update_leaderboard(
	# id: int   Eg: 56
	id: int,
	# adminUpdateLeaderboardRequest: AdminUpdateLeaderboardRequest
	# Leaderboard patch
	adminUpdateLeaderboardRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("PATCH")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/leaderboards/{id}".replace("{" + "id" + "}", _bzz_urlize_path_param(id))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_consumable_by_server := ['application/json']
	var bzz_found_producible_mime := false
	for bzz_mime in BZZ_PRODUCIBLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_consumable_by_server:
			bzz_headers["Content-Type"] = bzz_mime
			bzz_found_producible_mime = true
			break
	if not bzz_found_producible_mime:
		var error := ApiApiErrorClient.new()
		error.identifier = "admin_update_leaderboard.headers.content_type"
		error.message = "That endpoint only accepts %s as content type(s) and none are supported by this client."
		on_failure.call(error)
		return
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null
	bzz_body = adminUpdateLeaderboardRequest

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = AdminEndLeaderboard200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_update_leaderboard_threaded(
	# id: int   Eg: 56
	id: int,
	# adminUpdateLeaderboardRequest: AdminUpdateLeaderboardRequest
	# Leaderboard patch
	adminUpdateLeaderboardRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_update_leaderboard")
	bzz_callable.bind(
		id,
		adminUpdateLeaderboardRequest,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation adminUpdateLeaderboardRecord → PATCH /api/v1/admin/leaderboards/{id}/records/{record_id}
# Update leaderboard record (admin)
func admin_update_leaderboard_record(
	# id: int   Eg: 56
	id: int,
	# recordId: int   Eg: 56
	recordId: int,
	# adminUpdateLeaderboardRecordRequest: AdminUpdateLeaderboardRecordRequest
	# Record patch
	adminUpdateLeaderboardRecordRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("PATCH")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/leaderboards/{id}/records/{record_id}".replace("{" + "id" + "}", _bzz_urlize_path_param(id)).replace("{" + "record_id" + "}", _bzz_urlize_path_param(recordId))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_consumable_by_server := ['application/json']
	var bzz_found_producible_mime := false
	for bzz_mime in BZZ_PRODUCIBLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_consumable_by_server:
			bzz_headers["Content-Type"] = bzz_mime
			bzz_found_producible_mime = true
			break
	if not bzz_found_producible_mime:
		var error := ApiApiErrorClient.new()
		error.identifier = "admin_update_leaderboard_record.headers.content_type"
		error.message = "That endpoint only accepts %s as content type(s) and none are supported by this client."
		on_failure.call(error)
		return
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null
	bzz_body = adminUpdateLeaderboardRecordRequest

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = AdminSubmitLeaderboardScore200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_update_leaderboard_record_threaded(
	# id: int   Eg: 56
	id: int,
	# recordId: int   Eg: 56
	recordId: int,
	# adminUpdateLeaderboardRecordRequest: AdminUpdateLeaderboardRecordRequest
	# Record patch
	adminUpdateLeaderboardRecordRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_update_leaderboard_record")
	bzz_callable.bind(
		id,
		recordId,
		adminUpdateLeaderboardRecordRequest,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread
