extends ApiApiBeeClient
class_name AdminLobbiesApi

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# API AdminLobbiesApi
# Instantiate this object and use it to make requests to the API.

func _bzz_get_api_name() -> String:
	return "AdminLobbiesApi"


# Operation adminDeleteLobby → DELETE /api/v1/admin/lobbies/{id}
# Delete lobby by id (admin)
func admin_delete_lobby(
	# id: int   Eg: 56
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("DELETE")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/lobbies/{id}".replace("{" + "id" + "}", _bzz_urlize_path_param(id))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_delete_lobby_threaded(
	# id: int   Eg: 56
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_delete_lobby")
	bzz_callable.bind(
		id,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation adminListLobbies → GET /api/v1/admin/lobbies
# List all lobbies (admin)
func admin_list_lobbies(
	# title: String = ""   Eg: title_example
	title = "",
	# isHidden: String = ""   Eg: isHidden_example
	isHidden = "",
	# isLocked: String = ""   Eg: isLocked_example
	isLocked = "",
	# hasPassword: String = ""   Eg: hasPassword_example
	hasPassword = "",
	# minUsers: int   Eg: 56
	minUsers = null,
	# maxUsers: int   Eg: 56
	maxUsers = null,
	# page: int   Eg: 56
	page = null,
	# pageSize: int   Eg: 56
	pageSize = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("GET")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/lobbies"

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()
	bzz_query["title"] = title
	bzz_query["is_hidden"] = isHidden
	bzz_query["is_locked"] = isLocked
	bzz_query["has_password"] = hasPassword
	bzz_query["min_users"] = minUsers
	bzz_query["max_users"] = maxUsers
	bzz_query["page"] = page
	bzz_query["page_size"] = pageSize

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = AdminListLobbies200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_list_lobbies_threaded(
	# title: String = ""   Eg: title_example
	title = "",
	# isHidden: String = ""   Eg: isHidden_example
	isHidden = "",
	# isLocked: String = ""   Eg: isLocked_example
	isLocked = "",
	# hasPassword: String = ""   Eg: hasPassword_example
	hasPassword = "",
	# minUsers: int   Eg: 56
	minUsers = null,
	# maxUsers: int   Eg: 56
	maxUsers = null,
	# page: int   Eg: 56
	page = null,
	# pageSize: int   Eg: 56
	pageSize = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_list_lobbies")
	bzz_callable.bind(
		title,
		isHidden,
		isLocked,
		hasPassword,
		minUsers,
		maxUsers,
		page,
		pageSize,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation adminUpdateLobby → PATCH /api/v1/admin/lobbies/{id}
# Update lobby by id (admin)
func admin_update_lobby(
	# id: int   Eg: 56
	id: int,
	# adminUpdateLobbyRequest: AdminUpdateLobbyRequest
	# Lobby patch
	adminUpdateLobbyRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("PATCH")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/admin/lobbies/{id}".replace("{" + "id" + "}", _bzz_urlize_path_param(id))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_consumable_by_server := ['application/json']
	var bzz_found_producible_mime := false
	for bzz_mime in BZZ_PRODUCIBLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_consumable_by_server:
			bzz_headers["Content-Type"] = bzz_mime
			bzz_found_producible_mime = true
			break
	if not bzz_found_producible_mime:
		var error := ApiApiErrorClient.new()
		error.identifier = "admin_update_lobby.headers.content_type"
		error.message = "That endpoint only accepts %s as content type(s) and none are supported by this client."
		on_failure.call(error)
		return
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null
	bzz_body = adminUpdateLobbyRequest

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = AdminUpdateLobby200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func admin_update_lobby_threaded(
	# id: int   Eg: 56
	id: int,
	# adminUpdateLobbyRequest: AdminUpdateLobbyRequest
	# Lobby patch
	adminUpdateLobbyRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "admin_update_lobby")
	bzz_callable.bind(
		id,
		adminUpdateLobbyRequest,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread
