extends ApiApiBeeClient
class_name ChatApi

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# API ChatApi
# Instantiate this object and use it to make requests to the API.

func _bzz_get_api_name() -> String:
	return "ChatApi"


# Operation chatUnreadCount → GET /api/v1/chat/unread
# Get unread message count
#
# Get the number of unread messages for the current user in a chat conversation.
func chat_unread_count(
	# chatType: String = ""   Eg: chatType_example
	chatType: String,
	# chatRefId: int   Eg: 56
	chatRefId: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("GET")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/chat/unread"

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()
	bzz_query["chat_type"] = chatType
	bzz_query["chat_ref_id"] = chatRefId

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = ChatUnreadCount200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func chat_unread_count_threaded(
	# chatType: String = ""   Eg: chatType_example
	chatType: String,
	# chatRefId: int   Eg: 56
	chatRefId: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "chat_unread_count")
	bzz_callable.bind(
		chatType,
		chatRefId,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation deleteChatMessage → DELETE /api/v1/chat/messages/{id}
# Delete your own chat message
#
# Permanently delete a message you sent. Only the sender can delete their own message.
func delete_chat_message(
	# id: int   Eg: 56
	# Message ID
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("DELETE")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/chat/messages/{id}".replace("{" + "id" + "}", _bzz_urlize_path_param(id))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func delete_chat_message_threaded(
	# id: int   Eg: 56
	# Message ID
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "delete_chat_message")
	bzz_callable.bind(
		id,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation getChatMessage → GET /api/v1/chat/messages/{id}
# Get a single chat message
#
# Retrieve a single chat message by ID. Useful for refreshing a message after an update notification.
func get_chat_message(
	# id: int   Eg: 56
	# Message ID
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("GET")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/chat/messages/{id}".replace("{" + "id" + "}", _bzz_urlize_path_param(id))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = GetChatMessage200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func get_chat_message_threaded(
	# id: int   Eg: 56
	# Message ID
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "get_chat_message")
	bzz_callable.bind(
		id,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation listChatMessages → GET /api/v1/chat/messages
# List chat messages
#
# List messages for a lobby, group, party, or friend conversation. Paginated, newest first.
func list_chat_messages(
	# chatType: String = ""   Eg: chatType_example
	# Type of chat
	chatType: String,
	# chatRefId: int   Eg: 56
	# Reference ID (lobby_id, group_id, party_id, or friend user_id)
	chatRefId: int,
	# page: int = 1   Eg: 56
	# Page number
	page = 1,
	# pageSize: int = 25   Eg: 56
	# Items per page (max 100)
	pageSize = 25,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("GET")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/chat/messages"

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()
	bzz_query["chat_type"] = chatType
	bzz_query["chat_ref_id"] = chatRefId
	bzz_query["page"] = page
	bzz_query["page_size"] = pageSize

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = ListChatMessages200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func list_chat_messages_threaded(
	# chatType: String = ""   Eg: chatType_example
	# Type of chat
	chatType: String,
	# chatRefId: int   Eg: 56
	# Reference ID (lobby_id, group_id, party_id, or friend user_id)
	chatRefId: int,
	# page: int = 1   Eg: 56
	# Page number
	page = 1,
	# pageSize: int = 25   Eg: 56
	# Items per page (max 100)
	pageSize = 25,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "list_chat_messages")
	bzz_callable.bind(
		chatType,
		chatRefId,
		page,
		pageSize,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation markChatRead → POST /api/v1/chat/read
# Mark chat as read
#
# Update the read cursor for the current user in a chat conversation.
func mark_chat_read(
	# markChatReadRequest: MarkChatReadRequest
	# Read cursor
	markChatReadRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("POST")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/chat/read"

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_consumable_by_server := ['application/json']
	var bzz_found_producible_mime := false
	for bzz_mime in BZZ_PRODUCIBLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_consumable_by_server:
			bzz_headers["Content-Type"] = bzz_mime
			bzz_found_producible_mime = true
			break
	if not bzz_found_producible_mime:
		var error := ApiApiErrorClient.new()
		error.identifier = "mark_chat_read.headers.content_type"
		error.message = "That endpoint only accepts %s as content type(s) and none are supported by this client."
		on_failure.call(error)
		return
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null
	bzz_body = markChatReadRequest

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func mark_chat_read_threaded(
	# markChatReadRequest: MarkChatReadRequest
	# Read cursor
	markChatReadRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "mark_chat_read")
	bzz_callable.bind(
		markChatReadRequest,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation sendChatMessage → POST /api/v1/chat/messages
# Send a chat message
#
# Send a message to a lobby, group, party, or friend conversation. Requires authentication and membership/friendship.
func send_chat_message(
	# sendChatMessageRequest: SendChatMessageRequest
	# Chat message
	sendChatMessageRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("POST")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/chat/messages"

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_consumable_by_server := ['application/json']
	var bzz_found_producible_mime := false
	for bzz_mime in BZZ_PRODUCIBLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_consumable_by_server:
			bzz_headers["Content-Type"] = bzz_mime
			bzz_found_producible_mime = true
			break
	if not bzz_found_producible_mime:
		var error := ApiApiErrorClient.new()
		error.identifier = "send_chat_message.headers.content_type"
		error.message = "That endpoint only accepts %s as content type(s) and none are supported by this client."
		on_failure.call(error)
		return
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null
	bzz_body = sendChatMessageRequest

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = GetChatMessage200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func send_chat_message_threaded(
	# sendChatMessageRequest: SendChatMessageRequest
	# Chat message
	sendChatMessageRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "send_chat_message")
	bzz_callable.bind(
		sendChatMessageRequest,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation updateChatMessage → PATCH /api/v1/chat/messages/{id}
# Update your own chat message
#
# Edit the content or metadata of a message you sent. Only the sender can update their own message.
func update_chat_message(
	# id: int   Eg: 56
	# Message ID
	id: int,
	# updateChatMessageRequest: UpdateChatMessageRequest
	# Message update
	updateChatMessageRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("PATCH")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/chat/messages/{id}".replace("{" + "id" + "}", _bzz_urlize_path_param(id))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_consumable_by_server := ['application/json']
	var bzz_found_producible_mime := false
	for bzz_mime in BZZ_PRODUCIBLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_consumable_by_server:
			bzz_headers["Content-Type"] = bzz_mime
			bzz_found_producible_mime = true
			break
	if not bzz_found_producible_mime:
		var error := ApiApiErrorClient.new()
		error.identifier = "update_chat_message.headers.content_type"
		error.message = "That endpoint only accepts %s as content type(s) and none are supported by this client."
		on_failure.call(error)
		return
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null
	bzz_body = updateChatMessageRequest

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = GetChatMessage200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func update_chat_message_threaded(
	# id: int   Eg: 56
	# Message ID
	id: int,
	# updateChatMessageRequest: UpdateChatMessageRequest
	# Message update
	updateChatMessageRequest = null,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "update_chat_message")
	bzz_callable.bind(
		id,
		updateChatMessageRequest,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


