extends ApiApiBeeClient
class_name LeaderboardsApi

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# API LeaderboardsApi
# Instantiate this object and use it to make requests to the API.

func _bzz_get_api_name() -> String:
	return "LeaderboardsApi"


# Operation getLeaderboard → GET /api/v1/leaderboards/{id}
# Get a leaderboard by ID
#
# Return details for a specific leaderboard by its integer ID.
func get_leaderboard(
	# id: int   Eg: 56
	# Leaderboard ID
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("GET")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/leaderboards/{id}".replace("{" + "id" + "}", _bzz_urlize_path_param(id))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = ListLeaderboards200ResponseDataInner.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func get_leaderboard_threaded(
	# id: int   Eg: 56
	# Leaderboard ID
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "get_leaderboard")
	bzz_callable.bind(
		id,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation getMyRecord → GET /api/v1/leaderboards/{id}/records/me
# Get current user's record
#
# Return the authenticated user's record and rank on this leaderboard.
func get_my_record(
	# id: int   Eg: 56
	# Leaderboard ID
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("GET")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/leaderboards/{id}/records/me".replace("{" + "id" + "}", _bzz_urlize_path_param(id))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = ListLeaderboardRecords200ResponseDataInner.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func get_my_record_threaded(
	# id: int   Eg: 56
	# Leaderboard ID
	id: int,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "get_my_record")
	bzz_callable.bind(
		id,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation listLeaderboardRecords → GET /api/v1/leaderboards/{id}/records
# List leaderboard records
#
# Return ranked records for a leaderboard by its integer ID.
func list_leaderboard_records(
	# id: int   Eg: 56
	# Leaderboard ID
	id: int,
	# page: int = 1   Eg: 56
	# Page number
	page = 1,
	# pageSize: int = 25   Eg: 56
	# Page size (max 100)
	pageSize = 25,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("GET")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/leaderboards/{id}/records".replace("{" + "id" + "}", _bzz_urlize_path_param(id))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()
	bzz_query["page"] = page
	bzz_query["page_size"] = pageSize

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = ListLeaderboardRecords200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func list_leaderboard_records_threaded(
	# id: int   Eg: 56
	# Leaderboard ID
	id: int,
	# page: int = 1   Eg: 56
	# Page number
	page = 1,
	# pageSize: int = 25   Eg: 56
	# Page size (max 100)
	pageSize = 25,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "list_leaderboard_records")
	bzz_callable.bind(
		id,
		page,
		pageSize,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation listLeaderboards → GET /api/v1/leaderboards
# List leaderboards
#
# Return all leaderboards with optional filters. Results are ordered by end date (active/permanent first, then most recently ended).  **Common use cases:** - Get all leaderboards: `GET /api/v1/leaderboards` - Get all seasons of a leaderboard: `GET /api/v1/leaderboards?slug=weekly_kills` - Get active leaderboard by slug: `GET /api/v1/leaderboards?slug=weekly_kills&active=true` - Get only active leaderboards: `GET /api/v1/leaderboards?active=true` 
func list_leaderboards(
	# slug: String = ""   Eg: slug_example
	# Filter by slug (returns all seasons of that leaderboard, ordered by end date)
	slug = "",
	# active: String = ""   Eg: active_example
	# Filter by active status - 'true' or 'false' (omit for all)
	active = "",
	# orderBy: String = "ends_at"   Eg: orderBy_example
	# Order results by field. 'ends_at' (default) puts active first, then by end date. 'inserted_at' orders by creation date.
	orderBy = "ends_at",
	# startsAfter: String   Eg: 2013-10-20T19:20:30+01:00
	# Only leaderboards that started after this time (ISO 8601)
	startsAfter = null,
	# startsBefore: String   Eg: 2013-10-20T19:20:30+01:00
	# Only leaderboards that started before this time (ISO 8601)
	startsBefore = null,
	# endsAfter: String   Eg: 2013-10-20T19:20:30+01:00
	# Only leaderboards ending after this time (ISO 8601)
	endsAfter = null,
	# endsBefore: String   Eg: 2013-10-20T19:20:30+01:00
	# Only leaderboards ending before this time (ISO 8601)
	endsBefore = null,
	# page: int = 1   Eg: 56
	# Page number
	page = 1,
	# pageSize: int = 25   Eg: 56
	# Page size (max 100)
	pageSize = 25,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("GET")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/leaderboards"

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()
	bzz_query["slug"] = slug
	bzz_query["active"] = active
	bzz_query["order_by"] = orderBy
	bzz_query["starts_after"] = startsAfter
	bzz_query["starts_before"] = startsBefore
	bzz_query["ends_after"] = endsAfter
	bzz_query["ends_before"] = endsBefore
	bzz_query["page"] = page
	bzz_query["page_size"] = pageSize

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = ListLeaderboards200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func list_leaderboards_threaded(
	# slug: String = ""   Eg: slug_example
	# Filter by slug (returns all seasons of that leaderboard, ordered by end date)
	slug = "",
	# active: String = ""   Eg: active_example
	# Filter by active status - 'true' or 'false' (omit for all)
	active = "",
	# orderBy: String = "ends_at"   Eg: orderBy_example
	# Order results by field. 'ends_at' (default) puts active first, then by end date. 'inserted_at' orders by creation date.
	orderBy = "ends_at",
	# startsAfter: String   Eg: 2013-10-20T19:20:30+01:00
	# Only leaderboards that started after this time (ISO 8601)
	startsAfter = null,
	# startsBefore: String   Eg: 2013-10-20T19:20:30+01:00
	# Only leaderboards that started before this time (ISO 8601)
	startsBefore = null,
	# endsAfter: String   Eg: 2013-10-20T19:20:30+01:00
	# Only leaderboards ending after this time (ISO 8601)
	endsAfter = null,
	# endsBefore: String   Eg: 2013-10-20T19:20:30+01:00
	# Only leaderboards ending before this time (ISO 8601)
	endsBefore = null,
	# page: int = 1   Eg: 56
	# Page number
	page = 1,
	# pageSize: int = 25   Eg: 56
	# Page size (max 100)
	pageSize = 25,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "list_leaderboards")
	bzz_callable.bind(
		slug,
		active,
		orderBy,
		startsAfter,
		startsBefore,
		endsAfter,
		endsBefore,
		page,
		pageSize,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


# Operation listRecordsAroundUser → GET /api/v1/leaderboards/{id}/records/around/{user_id}
# List records around a user
#
# Return records centered around a specific user's rank.
func list_records_around_user(
	# id: int   Eg: 56
	# Leaderboard ID
	id: int,
	# userId: int   Eg: 56
	# User ID to center around
	userId: int,
	# limit: int = 11   Eg: 56
	# Total number of records to return
	limit = 11,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
):

	# Convert the String HTTP method to a Constant Godot understands
	var bzz_method := self._bzz_convert_http_method("GET")

	# Compute the URL path to the API resource
	var bzz_path := "/api/v1/leaderboards/{id}/records/around/{user_id}".replace("{" + "id" + "}", _bzz_urlize_path_param(id)).replace("{" + "user_id" + "}", _bzz_urlize_path_param(userId))

	# Collect the headers
	var bzz_headers := Dictionary()
	var bzz_mimes_produced_by_server := ['application/json']
	for bzz_mime in BZZ_CONSUMABLE_CONTENT_TYPES:
		if bzz_mime in bzz_mimes_produced_by_server:
			bzz_headers["Accept"] = bzz_mime
			break

	# Collect the query parameters
	# Note: we do not support multiple values for a single param (for now), nor arrays
	var bzz_query := Dictionary()
	bzz_query["limit"] = limit

	var bzz_body = null

	self._bzz_request(
		bzz_method, bzz_path, bzz_headers, bzz_query, bzz_body,
		func(bzz_response):
			bzz_response.data = ListRecordsAroundUser200Response.bzz_denormalize_single(bzz_response.data)
			on_success.call(bzz_response)
			,
		func(bzz_error):
			on_failure.call(bzz_error)
			,  # ざわ‥
	)


func list_records_around_user_threaded(
	# id: int   Eg: 56
	# Leaderboard ID
	id: int,
	# userId: int   Eg: 56
	# User ID to center around
	userId: int,
	# limit: int = 11   Eg: 56
	# Total number of records to return
	limit = 11,
	on_success: Callable = Callable(),  # func(response: ApiApiResponseClient)
	on_failure: Callable = Callable(),  # func(error: ApiApiErrorClient)
) -> Thread:
	var bzz_thread := Thread.new()
	var bzz_callable := Callable(self, "list_records_around_user")
	bzz_callable.bind(
		id,
		userId,
		limit,
		on_success,
		on_failure,
	)
	bzz_thread.start(bzz_callable)
	return bzz_thread


