import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
#
# Pinned to :gamend_host. A bare path resolves against the endpoint's own app,
# which is :gamend_web — whose priv holds no digest — so every asset URL went
# out undigested under a far-future cache header.
config :gamend_web, GamendWeb.Endpoint,
  cache_static_manifest: {:gamend_host, "priv/static/cache_manifest.json"}

config :gamend_web,
  gzip_static: true,
  # Brotli beats gzip by roughly 15-20% on CSS and JS. Plug.Static only reaches
  # for a `.br` when one is on disk, so this pairs with bin/compress-static in
  # `assets.deploy`; without those files it silently falls back to gzip.
  brotli_static: true

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Purge debug logs at compile-time in production builds.
# Note: this means `Logger.debug/1` calls won't be available in prod without rebuilding.
config :logger, compile_time_purge_matching: [[level_lower_than: :info]]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
