defmodule GameServerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :game_server_web

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # In production the Secure flag ensures the cookie is only sent over HTTPS.
  @session_options [
    store: :cookie,
    key: "_game_server_key",
    signing_salt: "G8u1px36",
    same_site: "Lax",
    secure: Mix.env() == :prod
  ]
  socket "/socket", GameServerWeb.UserSocket,
    websocket: [log: false, compress: true, max_frame_size: 131_072],
    longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, session: @session_options], log: false, compress: true],
    longpoll: [connect_info: [session: @session_options], log: false]

  # Serve ACME HTTP-01 challenges for Let's Encrypt before anything else.
  # This must come before force_ssl so challenges are served over plain HTTP.
  plug GameServerWeb.Plugs.AcmeChallenge

  # Set baseline security headers on every response (static, API, browser).
  plug GameServerWeb.Plugs.SecurityHeaders

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # Ensure certain well-known files are handled with strict headers before
  # Plug.Static decides how to serve them (files without extensions need
  # special handling for content-type and compression).
  plug GameServerHost.Plugs.WellKnown

  # Add COOP/COEP headers for Godot 4 web exports (SharedArrayBuffer)
  plug GameServerWeb.Plugs.GameHeaders

  # Serve host-owned static files (branding, game exports, robots.txt, .well-known)
  # directly from the host app.
  plug Plug.Static,
    at: "/",
    from: :game_server_host,
    gzip: not code_reloading?,
    only: ~w(images game favicon.ico robots.txt .well-known theme.css assets),
    cache_control_for_etags: "public, max-age=604800",
    cache_control_for_vsn_requests: "public, max-age=31536000, immutable"

  # Serve UI library static files (compiled JS/CSS, fonts) from game_server_web.
  plug Plug.Static,
    at: "/",
    from: :game_server_web,
    gzip: not code_reloading?,
    only: GameServerWeb.static_paths(),
    cache_control_for_etags: "public, max-age=604800",
    cache_control_for_vsn_requests: "public, max-age=31536000, immutable"

  # Serve blog/changelog images early, before the code-reloader
  # and session/CSRF plugs. This prevents concurrent image requests
  # from being serialized in dev mode.
  plug GameServerWeb.HostContentStatic

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :game_server_web
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug GameServerWeb.Plugs.RealIp
  plug GameServerWeb.Plugs.GeoCountry
  plug GameServerWeb.Plugs.IpBan
  plug GameServerWeb.Plugs.RequestTimer

  plug Plug.Telemetry,
    event_prefix: [:phoenix, :endpoint],
    log: {__MODULE__, :access_log_level, []}

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    length: 1_048_576,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head

  # Skip session for API v1 requests — they use JWT auth, not cookies
  @compiled_session_opts Plug.Session.init(@session_options)
  plug :maybe_session

  defp maybe_session(%{path_info: ["api", "v1" | _]} = conn, _opts), do: conn
  defp maybe_session(conn, _opts), do: Plug.Session.call(conn, @compiled_session_opts)

  # Extract optional locale prefix from URL (e.g. /es/...) and set Gettext locale
  plug GameServerWeb.Plugs.LocalePath

  plug GameServerWeb.Plugs.DynamicCors

  plug GameServerWeb.Plugs.RateLimiter

  plug GameServerHost.Router

  # Cache the access log level in persistent_term to avoid
  # Application.get_env on every request.
  @access_log_pt_key {__MODULE__, :access_log_level}
  def access_log_level(_conn) do
    case :persistent_term.get(@access_log_pt_key, :not_set) do
      :not_set ->
        level =
          case Application.get_env(:game_server_web, __MODULE__)[:access_log] do
            level when level in [:debug, :info, :warning, :error] -> level
            false -> false
            _ -> :debug
          end

        :persistent_term.put(@access_log_pt_key, level)
        level

      cached ->
        cached
    end
  end
end
